# Generated by Django 4.0.3 on 2022-09-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_staffrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
